name: Deploy to server

on: [push]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      env:
        USERNAME: ${{ secrets.USER_NAME }}
        HOST: ${{ secrets.HOST }}
        SCRIPT: ${{ secrets.SCRIPT }}
        KEY: ${{ secrets.SSH_DEPLOYMENT_KEY }}
